version: '3.4'

services:
  db:
    container_name: Banco_DB
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "banco*123"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1434"

  clientes.api:
    image: ${DOCKER_REGISTRY-}clientesapi
    build:
      context: .
      dockerfile: Clientes.API/Dockerfile

  cuentas.api:
    image: ${DOCKER_REGISTRY-}cuentasapi
    build:
      context: .
      dockerfile: Cuentas.API/Dockerfile

  movimientos.api:
    image: ${DOCKER_REGISTRY-}movimientosapi
    build:
      context: .
      dockerfile: Movimientos.API/Dockerfile

  api.gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API.Gateway/Dockerfile

networks: 
  default:
    external:
      name: banconet


##
#networks: 
#  banconet:
#    driver: bridge
#    driver_opts:
#        com.docker.network.enable_ipv6: "true"
    #external:
    #  name: banconet

##