version: '3.4'

services:
  clientes.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6110:80"

  cuentas.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6111:80"


  movimientos.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6112:80"


  api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Cliente=http://api.gateway
      - Services__Cuenta=http://api.gateway
    depends_on:
      - clientes.api
      - cuentas.api
    ports:
      - "6113:80"

