version: '3.4'

services:
  db:
    container_name: Banco_DB
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "banco*123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  clientes.api:
    image: ${DOCKER_REGISTRY-}clientesapi
    build:
      context: .
      dockerfile: Clientes.API/Dockerfile

  cuentas.api:
    image: ${DOCKER_REGISTRY-}cuentasapi
    build:
      context: .
      dockerfile: Cuentas.API/Dockerfile

  movimientos.api:
    image: ${DOCKER_REGISTRY-}movimientosapi
    build:
      context: .
      dockerfile: Movimientos.API/Dockerfile

  api.gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API.Gateway/Dockerfile

networks: 
  specific-network-name:
    name: banconet
    driver: bridge
    driver_opts:
        com.docker.network.enable_ipv6: "true"
